/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BugsRouteImport } from './routes/bugs'
import { Route as EngineeringHealthRouteImport } from './routes/engineering-health'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ManualLogRouteImport } from './routes/manual-log'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BugsRoute = BugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringHealthRoute = EngineeringHealthRouteImport.update({
  id: '/engineering-health',
  path: '/engineering-health',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualLogRoute = ManualLogRouteImport.update({
  id: '/manual-log',
  path: '/manual-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bugs': typeof BugsRoute
  '/engineering-health': typeof EngineeringHealthRoute
  '/integrations': typeof IntegrationsRoute
  '/manual-log': typeof ManualLogRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bugs': typeof BugsRoute
  '/engineering-health': typeof EngineeringHealthRoute
  '/integrations': typeof IntegrationsRoute
  '/manual-log': typeof ManualLogRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bugs': typeof BugsRoute
  '/engineering-health': typeof EngineeringHealthRoute
  '/integrations': typeof IntegrationsRoute
  '/manual-log': typeof ManualLogRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bugs'
    | '/engineering-health'
    | '/integrations'
    | '/manual-log'
    | '/reports'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bugs'
    | '/engineering-health'
    | '/integrations'
    | '/manual-log'
    | '/reports'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/bugs'
    | '/engineering-health'
    | '/integrations'
    | '/manual-log'
    | '/reports'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BugsRoute: typeof BugsRoute
  EngineeringHealthRoute: typeof EngineeringHealthRoute
  IntegrationsRoute: typeof IntegrationsRoute
  ManualLogRoute: typeof ManualLogRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugs': {
      id: '/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof BugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering-health': {
      id: '/engineering-health'
      path: '/engineering-health'
      fullPath: '/engineering-health'
      preLoaderRoute: typeof EngineeringHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-log': {
      id: '/manual-log'
      path: '/manual-log'
      fullPath: '/manual-log'
      preLoaderRoute: typeof ManualLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BugsRoute: BugsRoute,
  EngineeringHealthRoute: EngineeringHealthRoute,
  IntegrationsRoute: IntegrationsRoute,
  ManualLogRoute: ManualLogRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
