/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiUsageRouteImport } from './routes/ai-usage'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EngineeringHealthRouteImport } from './routes/engineering-health'
import { Route as EpicsRouteImport } from './routes/epics'
import { Route as InfraSpendRouteImport } from './routes/infra-spend'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManualLogRouteImport } from './routes/manual-log'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as BugsIndexRouteImport } from './routes/bugs.index'
import { Route as BugsBugIdRouteImport } from './routes/bugs.$bugId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiUsageRoute = AiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringHealthRoute = EngineeringHealthRouteImport.update({
  id: '/engineering-health',
  path: '/engineering-health',
  getParentRoute: () => rootRouteImport,
} as any)
const EpicsRoute = EpicsRouteImport.update({
  id: '/epics',
  path: '/epics',
  getParentRoute: () => rootRouteImport,
} as any)
const InfraSpendRoute = InfraSpendRouteImport.update({
  id: '/infra-spend',
  path: '/infra-spend',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualLogRoute = ManualLogRouteImport.update({
  id: '/manual-log',
  path: '/manual-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const BugsIndexRoute = BugsIndexRouteImport.update({
  id: '/bugs/',
  path: '/bugs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BugsBugIdRoute = BugsBugIdRouteImport.update({
  id: '/bugs/$bugId',
  path: '/bugs/$bugId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-usage': typeof AiUsageRoute
  '/backlog': typeof BacklogRoute
  '/dashboard': typeof DashboardRoute
  '/engineering-health': typeof EngineeringHealthRoute
  '/epics': typeof EpicsRoute
  '/infra-spend': typeof InfraSpendRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/manual-log': typeof ManualLogRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/bugs/$bugId': typeof BugsBugIdRoute
  '/bugs/': typeof BugsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-usage': typeof AiUsageRoute
  '/backlog': typeof BacklogRoute
  '/dashboard': typeof DashboardRoute
  '/engineering-health': typeof EngineeringHealthRoute
  '/epics': typeof EpicsRoute
  '/infra-spend': typeof InfraSpendRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/manual-log': typeof ManualLogRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/bugs/$bugId': typeof BugsBugIdRoute
  '/bugs': typeof BugsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-usage': typeof AiUsageRoute
  '/backlog': typeof BacklogRoute
  '/dashboard': typeof DashboardRoute
  '/engineering-health': typeof EngineeringHealthRoute
  '/epics': typeof EpicsRoute
  '/infra-spend': typeof InfraSpendRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/manual-log': typeof ManualLogRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/bugs/$bugId': typeof BugsBugIdRoute
  '/bugs/': typeof BugsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-usage'
    | '/backlog'
    | '/dashboard'
    | '/engineering-health'
    | '/epics'
    | '/infra-spend'
    | '/integrations'
    | '/login'
    | '/manual-log'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/bugs/$bugId'
    | '/bugs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-usage'
    | '/backlog'
    | '/dashboard'
    | '/engineering-health'
    | '/epics'
    | '/infra-spend'
    | '/integrations'
    | '/login'
    | '/manual-log'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/bugs/$bugId'
    | '/bugs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-usage'
    | '/backlog'
    | '/dashboard'
    | '/engineering-health'
    | '/epics'
    | '/infra-spend'
    | '/integrations'
    | '/login'
    | '/manual-log'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/setup'
    | '/bugs/$bugId'
    | '/bugs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiUsageRoute: typeof AiUsageRoute
  BacklogRoute: typeof BacklogRoute
  DashboardRoute: typeof DashboardRoute
  EngineeringHealthRoute: typeof EngineeringHealthRoute
  EpicsRoute: typeof EpicsRoute
  InfraSpendRoute: typeof InfraSpendRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  ManualLogRoute: typeof ManualLogRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  BugsBugIdRoute: typeof BugsBugIdRoute
  BugsIndexRoute: typeof BugsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-usage': {
      id: '/ai-usage'
      path: '/ai-usage'
      fullPath: '/ai-usage'
      preLoaderRoute: typeof AiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering-health': {
      id: '/engineering-health'
      path: '/engineering-health'
      fullPath: '/engineering-health'
      preLoaderRoute: typeof EngineeringHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epics': {
      id: '/epics'
      path: '/epics'
      fullPath: '/epics'
      preLoaderRoute: typeof EpicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra-spend': {
      id: '/infra-spend'
      path: '/infra-spend'
      fullPath: '/infra-spend'
      preLoaderRoute: typeof InfraSpendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-log': {
      id: '/manual-log'
      path: '/manual-log'
      fullPath: '/manual-log'
      preLoaderRoute: typeof ManualLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugs/': {
      id: '/bugs/'
      path: '/bugs'
      fullPath: '/bugs/'
      preLoaderRoute: typeof BugsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugs/$bugId': {
      id: '/bugs/$bugId'
      path: '/bugs/$bugId'
      fullPath: '/bugs/$bugId'
      preLoaderRoute: typeof BugsBugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiUsageRoute: AiUsageRoute,
  BacklogRoute: BacklogRoute,
  DashboardRoute: DashboardRoute,
  EngineeringHealthRoute: EngineeringHealthRoute,
  EpicsRoute: EpicsRoute,
  InfraSpendRoute: InfraSpendRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  ManualLogRoute: ManualLogRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  BugsBugIdRoute: BugsBugIdRoute,
  BugsIndexRoute: BugsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
